name       : perl-test-deep
version    : '1.204'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Test-Deep-1.204.tar.gz : b6591f6ccdd853c7efc9ff3c5756370403211cffe46047f082b1cd1611a84e5f
homepage   : https://metacpan.org/pod/Test::Deep
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : This module gives you lots of flexibility when testing deep structres
description: |
    This module gives you lots of flexibility when testing deep structres.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
