name       : perl-test-deep
version    : '1.127'
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Test-Deep-1.127.tar.gz : b78cfc59c41ba91f47281e2c1d2bfc4b3b1b42bfb76b4378bc88cc37b7af7268
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : This module gives you lots of flexibility when testing deep structres.
description: |
    This module gives you lots of flexibility when testing deep structres.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
